# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyadar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
