# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyadar', '0002_assignment_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='created_date',
        ),
    ]
