# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyadar', '0003_remove_assignment_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
