# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 19:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyadar', '0004_assignment_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='expired_date',
            field=models.DateField(default=datetime.date(2017, 11, 8)),
        ),
    ]
