# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 08:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oyadar', '0005_assignment_expired_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssigmentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_detail', models.TextField()),
                ('question_note', models.TextField()),
                ('question_type', models.IntegerField()),
                ('answer_id', models.IntegerField()),
                ('ordering', models.IntegerField(default=1)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_detail', models.TextField()),
                ('ordering', models.IntegerField()),
                ('create_date', models.DateField(default=datetime.date(2017, 11, 11))),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oyadar.AssigmentQuestion')),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='expired_date',
            field=models.DateField(default=datetime.date(2017, 11, 11)),
        ),
        migrations.AddField(
            model_name='assigmentquestion',
            name='assignment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oyadar.Assignment'),
        ),
    ]
