# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 08:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('oyadar', '0007_auto_20171111_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='expired_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 11, 8, 3, 13, 875241, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assignmentanswer',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 11, 8, 3, 13, 877788, tzinfo=utc)),
        ),
    ]
