# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oyadar', '0008_auto_20171111_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='expired_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assignmentanswer',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
