# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyadar', '0010_remove_assigmentquestion_answer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigmentquestion',
            name='answer_id',
            field=models.IntegerField(default=0),
        ),
    ]
