# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyadar', '0012_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=150)),
                ('student_last_name', models.CharField(max_length=150)),
                ('student_email', models.CharField(max_length=100)),
                ('student_password', models.CharField(max_length=64)),
            ],
        ),
    ]
