# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyadar', '0014_testuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_detail',
            field=models.TextField(default=''),
        ),
    ]
