# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyadar', '0017_auto_20171130_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscore',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
    ]
