# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyadar', '0019_class_is_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='professor_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
