# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyadar', '0009_auto_20171111_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigmentquestion',
            name='answer_id',
            field=models.IntegerField(default=0),
        ),
    ]
